FROM node:20-bullseye

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml tsconfig.json ./ 
COPY src/ ./src/   
RUN npm install -g pnpm

RUN pnpm install
COPY build/ ./build/

EXPOSE 3000
# EXPOSE 8085
CMD ["sh", "-c", "pnpm run websocket & pnpm start"]
